[package]
name = "fwar"
version = "0.1.0"
authors = ["selfup <boudinot.regis@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "0.3.2"
